security:
    encoders:
        Gilles\UserRestBundle\Entity\Utilisateur: 
          algorithm:  sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
      main: 
        entity: { class: Gilles\UserRestBundle\Entity\Utilisateur, property: mail }

    firewalls:
        login:
            pattern:  ^/secure/login$
            security: false

        secured_area:
            pattern:    ^/secure/
            form_login:
                check_path: _hello_security_check
                login_path: _hello_login
            logout:
                path:   _hello_logout
                target: _hello_list
            anonymous: ~

    access_control:
        - { path: ^/secure, roles: ROLE_ADMIN }
