security:
    encoders:
        Gilles\HelloBundle\Entity\Utilisateur: 
          algorithm:  sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
      main: 
        entity: { class: Gilles\UserRestBundle\Entity\Utilisateur, property: mail }

    firewalls:
        #dev:
        #    pattern:  ^/(_(profiler|wdt)|css|images|js)/
        #    security: false

        login:
            pattern:  ^/secure/login$
            security: false

        secured_area:
            pattern:    ^/secure/
            form_login:
                check_path: _hello_security_check
                login_path: _hello_login
            logout:
                path:   _hello_logout
                target: _hello_list
            anonymous: ~

    access_control:
        #- { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        - { path: ^/secure, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
