parameters:
#    gilles_hello.example.class: Gilles\UserRestBundle\Example

services:
#    gilles_hello.example:
#        class: %gilles_hello.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
